###########
# General #
###########
project_name: "" # baseline for synthetic experiments
experiment_name: "adaptive_schedule_12"
max_iterations: 300 
tolerance: 1.e-6
# verbose_level: 0 
repetitions: 1
seed: 31415
log_every: [1,1,1,1,1] 
plot_every: [1,1,1,1,1,1,1]

plot_schedules: [1,1,1,1,1,1,1]

#########
# Data # 
#########

# other possible datasets: 'w1a', 'w8a', 'duke', 'gisette_scale', 'synthetic'
data_path: 'datasets/'
dataset: 'gisette' 

# for synthetic dataset
n: 100
mu: 0.05 # smaller mu makes problem more difficult
replication_factor: 1
correlated_data: 'high' # no, medium, high


############# 
# Optimizer #
############# 

optimizer: 'SSCN' # possible optimizers: CD, SSCN

# TODO: currently not considered, only running logsumexp experiments
# possible loss functions: logsumexp, square_loss_w_nonconv_reg, non_linear_least_square_w_nonconv_reg
loss_func: 'logreg_nonconv'

# possible subsolvers: exact, lanczos, cauchy_pt 
# TODO: Add nonlinear_CG_method
subsolver: 'exact'
# possible coordinate schedules: constant, linear, quadratic, exponential, adaptive
coordinate_schedule: 'adaptive'
# TODO: currently only allows one lambda
lambdas: [1.e-1] # weight of non-convex regularizer
taus: [50] 
# cs: [0.1, 0.5, 1, 1.5, 1.7]
cs: [10]
beta: [0.2]
# for linear schedule: 
scales_lin: [0.1, 0.3, 0.5]
# for quadratic schedule:
scales_quad: [0.001, 0.002]
# for exponential schedule:
exps: [0.004, 0.005, 0.01, 0.02]
# for adaptie schedule:
eps_1: 0.01 
eps_2: 0.01
# for jump schedule, i.e. jumping from one constant coordinate to another const. coordinate schedule after some number of iterations
jump_iters: [0,1000,2000,3000]
jump_coord: 100